# Generated by Django 6.0 on 2026-05-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('english', '英語'), ('python', 'Python'), ('django', 'Django'), ('automation', '自動化'), ('fx', 'FX')], max_length=20),
        ),
    ]
